name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      pnpm-version:
        required: false
        type: string
        default: '9.15.3'
    secrets:
      NODE_VERSION:
        required: true
      CHROMATIC_PROJECT_TOKEN:
        required: true
      TOKEN_GITHUB:
        required: true
      TOKEN_SONAR:
        required: true
      SONAR_ORGANISATION:
        required: true
      SONAR_PROJECT_KEY:
        required: true
      SONAR_PROJECT_NAME:
        required: true

env:
  NODE_VERSION: ${{ secrets.NODE_VERSION }}
  CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
  TOKEN_SONAR: ${{ secrets.TOKEN_SONAR }}
  SONAR_ORGANISATION: ${{ secrets.SONAR_ORGANISATION }}
  SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
  SONAR_PROJECT_NAME: ${{ secrets.SONAR_PROJECT_NAME }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install Packages
        run: pnpm install

      - name: Build
        run: |
          pnpm run build
          pnpm run lint
        env:
          NODE_ENV: 'development'

      - name: Test
        run: pnpm run test:coverage
        env:
          NODE_ENV: 'development'

      - name: Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ env.CHROMATIC_PROJECT_TOKEN }}

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./coverage

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

  sonarcloud:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: ./coverage

      - name: SonarCloud Scan & Quality Gate
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ env.TOKEN_GITHUB }}
          SONAR_TOKEN: ${{ env.TOKEN_SONAR }}
        with:
          args: >
            -Dsonar.organization=${{ env.SONAR_ORGANISATION }}
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.projectName=${{ env.SONAR_PROJECT_NAME }}
            -Dsonar.qualitygate.wait=true
            -Dsonar.coverage.exclusions=src/setupTests.ts,src/reportWebVitals.ts,src/index.tsx
            -Dsonar.typescript.lcov.reportPaths=./coverage/lcov.info
